//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneStoreManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportManagement
    {
        public int IDImManagement { get; set; }
        public int IDEmployee { get; set; }
        public int IDPhone { get; set; }
        public System.DateTime ImportDate { get; set; }
        public int UnitPrice { get; set; }
        public int Quantity { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Phone Phone { get; set; }
    }
}
