//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneStoreManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryManagement
    {
        public int IDInvenManagement { get; set; }
        public int IDPhone { get; set; }
        public int Quantity { get; set; }
    
        public virtual Phone Phone { get; set; }
    }
}
