//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneStoreManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_()
        {
            this.ExportManagements = new HashSet<ExportManagement>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Transaction_ = new HashSet<Transaction_>();
        }
    
        public int IDOrder { get; set; }
        public Nullable<int> IDCustomer { get; set; }
        public Nullable<int> IDEmployeeCreate { get; set; }
        public Nullable<int> IDEmployeeEdit { get; set; }
        public System.DateTime TimeOrder { get; set; }
        public int Total { get; set; }
        public int IDState { get; set; }
        public int IDTypeOrder { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExportManagement> ExportManagements { get; set; }
        public virtual State State { get; set; }
        public virtual TypeOrder TypeOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_> Transaction_ { get; set; }
    }
}
