//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneStoreManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phone()
        {
            this.ImportManagements = new HashSet<ImportManagement>();
            this.InventoryManagements = new HashSet<InventoryManagement>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int IDPhone { get; set; }
        public string NamePhone { get; set; }
        public int RAM { get; set; }
        public int ROM { get; set; }
        public string ScreenSize { get; set; }
        public int BateryCapacity { get; set; }
        public int CameraResolution { get; set; }
        public int Price { get; set; }
        public string Operating { get; set; }
        public string IDBrand { get; set; }
        public Nullable<int> IDPhoneType { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportManagement> ImportManagements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryManagement> InventoryManagements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual PhoneType PhoneType { get; set; }
    }
}
