//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneStoreManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_
    {
        public int IDTransaction { get; set; }
        public Nullable<int> IDOrder { get; set; }
        public string PaymentMethods { get; set; }
        public System.DateTime DateOfPayment { get; set; }
        public int Price { get; set; }
        public int IDDiscount { get; set; }
    
        public virtual Discount Discount { get; set; }
        public virtual Order_ Order_ { get; set; }
    }
}
